samples:
	x86_64-w64-mingw32-gcc decltest.c -c -o obj/decltest64.o -m64
	x86_64-w64-mingw32-gcc getdc.c -c -o obj/getdc64.o -m64
	i686-w64-mingw32-gcc decltest.c -c -o obj/decltest86.o -m32
	i686-w64-mingw32-gcc getdc.c -c -o obj/getdc86.o -m32

contact_harvester:
	x86_64-w64-mingw32-gcc harvester.c -c -o obj/harvester64.o -m64
	i686-w64-mingw32-gcc harvester.c -c -o obj/harvester86.o -m32

shadowclone:
	x86_64-w64-mingw32-gcc shadowclone.c -c -o obj/shadowclone64.o -m64
	i686-w64-mingw32-gcc shadowclone.c -c -o obj/shadowclone86.o -m32

vainject:
	x86_64-w64-mingw32-gcc vainject.c -c -o obj/vainject64.o -m64
	i686-w64-mingw32-gcc vainject.c -c -o obj/vainject86.o -m32
